development:
  server: "http://gallo-messaging-node.herokuapp.com/faye"
  secret_token: "anything"
test:
  server: "http://gallo-messaging-node.herokuapp.com/faye"
  secret_token: "anything"
production:
  server: "http://gallo-messaging-node.herokuapp.com/faye"
  secret_token: "anything"
  signature_expiration: 3600 # one hour
